In [2]:
print("Day1")

Day1

In [3]:
# Machine Learning
# data(50) --> x(input_data) , y(output_data)
# x = x_train , x_test
# y = y_train , y_test
# for machine training we will pass (x_train , y_train)
# for machine testing (x_test) --> y_pred

# 1+1 = 2
# 1+2 = 3
# 1+4 = 5
# 1+6 = 7
# 1+7 = 8
# 1+8 = 9

# x = (1+1, 1+2, 1+4, 1+6 .... 1+8)
# y = (2,3,5,7,8,9)
# x_train = (1+1,1+2 , 1+4 , 1+6)
# x_test = (1+7,1+8)
# y_train = (2,3,5,7)
# y_test = (8,9)

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Regex\\Ml_REGex\\covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [6]:
df.shape

(100, 6)

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
df['fever'] = df['fever'].fillna(df['fever'].mean()) #Fill the NUll Values By the avg values

In [9]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [10]:
x =df.drop(columns='has_covid')  ### Input Data 
x

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [11]:
y =df['has_covid']  ## Target or Output Data
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: str

In [12]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train , x_test , y_train , y_test =  train_test_split(x,y , test_size=0.2 , random_state= 42 )

In [15]:
print("total Data Shape: ",df.shape)

print("----------------------------")

print("Input Data Shape: ",x.shape)
print("x_train data Shape:",x_train.shape)
print("x_test data Shape:",x_test.shape)

print("----------------------------")

print("Output Data Shape : ",y.shape )
print("y_train data Shape : ",y_train.shape)
print("y_test Data Shape: ",y_test.shape)

total Data Shape:  (100, 6)
----------------------------
Input Data Shape:  (100, 5)
x_train data Shape: (80, 5)
x_test data Shape: (20, 5)
----------------------------
Output Data Shape :  (100,)
y_train data Shape :  (80,)
y_test Data Shape:  (20,)

In [16]:
df1 = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Regex\\Ml_REGex\\placement.csv")
df1

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [17]:
df1.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [18]:
x = df1.drop(columns='placed') #input Data
x

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]

In [19]:
y = df1['placed']
y

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train , x_test , y_train , y_test  = train_test_split(x,y,test_size=0.2 , random_state=42)

In [22]:
print("total Data Shape: ",df1.shape)

print("----------------------------")

print("Input Data Shape: ",x.shape)
print("x_train data Shape:",x_train.shape)
print("x_test data Shape:",x_test.shape)

print("----------------------------")

print("Output Data Shape : ",y.shape )
print("y_train data Shape : ",y_train.shape)
print("y_test Data Shape: ",y_test.shape)

total Data Shape:  (100, 3)
----------------------------
Input Data Shape:  (100, 2)
x_train data Shape: (80, 2)
x_test data Shape: (20, 2)
----------------------------
Output Data Shape :  (100,)
y_train data Shape :  (80,)
y_test Data Shape:  (20,)

In [23]:
print("Hello World")

Hello World