In [66]:
print("Day 10")

Day 10

Column Transformer

In [67]:
import pandas as pd 
import numpy as np 
from sklearn.impute import SimpleImputer ### For Filling The missing Values 
from sklearn.preprocessing import OneHotEncoder ##Encoding

from  sklearn.preprocessing import OrdinalEncoder ##Encoding

In [4]:
df = pd.read_csv("covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [69]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [72]:
x_train , x_test , y_train , y_test= train_test_split(x,y,test_size=0.2 , random_state=42)

In [9]:
x_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

Manually Type Output

In [10]:
# adding Simple Imputer to fever Columns 
si = SimpleImputer(strategy='mean') #Like Nupy Fillna Method --> To fill the missing values

x_train_fever = si.fit_transform(x_train[['fever']])

# Also THe Test Data
x_test_fever = si.fit_transform(x_test[['fever']])


x_train_fever.shape

(80, 1)

In [75]:
# Ordinal Encoding --> Cough Column
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])


# Also Test Data

# x_test_cough = oe.fit_transform(x_test[['cough']])


x_train_cough.shape

(80, 1)

In [76]:
# OneHotEncoder --> Gender , City

ohe = OneHotEncoder(drop='first' , sparse_output= False)

x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city = ohe.fit_transform(x_test[['gender' , 'city']])

x_train_gender_city.shape

(80, 4)

In [77]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [78]:
x_train_transformed = np.concatenate((x_train_age, x_train_fever , x_train_cough , x_train_gender_city),axis=1)

In [79]:
x_train_transformed.shape

(80, 7)

# By The Help Of Column Transform

In [80]:
from sklearn.compose import ColumnTransformer

In [81]:
transformer = ColumnTransformer(transformers=[
    ('tnf1' , SimpleImputer() , ['fever']), # In a Fever Column By The Help Of Si we fill missing values by mean , median , mode
    
    ('tnf2' , OrdinalEncoder(categories=[['Mild','Strong']]),['cough']), # By The Process We Ecode Our Data
    
    ('tnf3' , OneHotEncoder(sparse_output= False , drop='first'),['gender' , 'city'])
] , remainder='passthrough' ) #Remainder ='Passthrough' --> it means rest all the columns remain same

In [82]:
transformer.fit_transform(x_train).shape

(80, 7)

In [83]:
df = pd.read_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [84]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [85]:
x = df.drop(columns=['charges'])
y= df['charges']

In [86]:
x_train , x_test, y_train , y_test = train_test_split(x, y , test_size=0.2)

In [87]:
from sklearn.compose import ColumnTransformer

In [88]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', OrdinalEncoder(categories=[['male', 'female']]), ['sex']),
    
    ('tnf2', OneHotEncoder(sparse_output=False, drop='first'), ['smoker', 'region'])
],
remainder='passthrough')

In [89]:
transformer.fit_transform(x_train).shape

(1070, 8)

In [26]:
df = pd.read_csv('covid_toy.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [27]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [28]:
x_train , x_test , y_train , y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'] , test_size=0.2)

In [37]:
si = SimpleImputer(strategy='mean')

x_train_fever = si.fit_transform(x_train[['fever']])

x_test_fever = si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [31]:
oe = OrdinalEncoder(categories=[['Mild' , 'Strong']])

x_train_cough = oe.fit_transform(x_train[['cough']])

x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [32]:
ohe = OneHotEncoder(sparse_output=False , drop='first')

In [36]:
x_train_gender_city = ohe.fit_transform(x_train[['gender' , 'city']])
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city.shape

(80, 4)

In [40]:
x_train_age = x_train.drop(columns=['gender','fever','city' , 'cough' ]).values
x_test_age = x_test.drop(columns=['gender','fever','city','cough']).values

In [42]:
transformer = np.concatenate((x_train_fever , x_train_cough , x_train_age , x_train_gender_city),axis=1)

In [43]:
transformer.shape

(80, 7)

In [44]:
from sklearn.compose import ColumnTransformer

In [54]:
transformer1= ColumnTransformer(transformers=[
    ('tnf1' , SimpleImputer(),['fever']),
    ('tnf2',OneHotEncoder(sparse_output=False,drop='first') , ['gender' , 'city'] ),
    ('tnf3' , OrdinalEncoder(categories=[['Mild' ,'Strong']]) ,['cough'])
],remainder='passthrough')

In [55]:
transformer1.fit_transform(x_train).shape

(80, 7)