In [59]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv("tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [47]:
x = df.drop(columns='total_bill')
y = df['total_bill']

In [33]:
df['sex'] = df['sex'].map({"Male":0,"Female":1})
df['smoker'] = df['smoker'].map({"Yes":0,"No":1})
df['time'] = df['time'].map({"Dinner":0,"Lunch":1})
df['day'] = df['day'].map({"Sun":0,"Sat":1,'Thur':2,"Fri":3})

In [34]:
df

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    1       1    0     0     2
1         10.34  1.66    0       1    0     0     3
2         21.01  3.50    0       1    0     0     3
3         23.68  3.31    0       1    0     0     2
4         24.59  3.61    1       1    0     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    0       1    1     0     3
240       27.18  2.00    1       0    1     0     2
241       22.67  2.00    0       0    1     0     2
242       17.82  1.75    0       1    1     0     2
243       18.78  3.00    1       1    2     0     2

[244 rows x 7 columns]

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [53]:
from sklearn.preprocessing import StandardScaler

In [54]:
sc = StandardScaler()

In [55]:
np.round(x_train.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean     3.09    0.35    0.62    1.10    0.27    2.57
std      1.43    0.48    0.49    0.95    0.45    0.94
min      1.00    0.00    0.00    0.00    0.00    1.00
25%      2.00    0.00    0.00    0.00    0.00    2.00
50%      3.00    0.00    1.00    1.00    0.00    2.00
75%      3.70    1.00    1.00    2.00    1.00    3.00
max     10.00    1.00    1.00    3.00    1.00    6.00

In [56]:
x_train_sc = sc.fit_transform(x_train)

In [57]:
x_train_new = pd.DataFrame(x_train_sc, columns = x_train.columns)

In [58]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean    -0.00    0.00   -0.00   -0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00    1.00    1.00
min     -1.46   -0.73   -1.26   -1.17   -0.61   -1.68
25%     -0.76   -0.73   -1.26   -1.17   -0.61   -0.61
50%     -0.06   -0.73    0.79   -0.11   -0.61   -0.61
75%      0.43    1.37    0.79    0.95    1.64    0.45
max      4.85    1.37    0.79    2.01    1.64    3.65