In [72]:
print("Day 5")

Day 5

In [73]:
# Normalization --> Usign MinMaxScaling
# data Min_Value = 0  , Max_Value =1

In [74]:
# playStore --> Different Different Aaps --> 1 App Dowanloads 4.2k , 1 App Dowanloads 2.3 M , 1 App Dowanload 650 

#  In this condition , if i apply any operation , then it will return hugh  number and we cannot perform any visulization bcz it will create zig zig condition 
# office me Employees Salary -->  5k , 50k , 2lakhs  , 10lakhs , --> Data Scale --> MinMaxScaling

In [98]:
import numpy as np
import pandas as pd

In [99]:
df = pd.read_csv("covid_toy.csv")

In [100]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [101]:
df.drop(columns=['city'], inplace=True)

# Step1 : Convert Categorial to Numberical

In [102]:
df['gender'] = df['gender'].map({"Male":0 , "Female":1})
df['cough'] = df['cough'].map({"Mild":0 , "Strong":1})
df['has_covid'] = df['has_covid'].map({"No":0 , "Yes":1})

In [103]:
df

    age  gender  fever  cough  has_covid
0    60       0  103.0      0          0
1    27       0  100.0      0          1
2    42       0  101.0      0          0
3    31       1   98.0      0          0
4    65       1  101.0      0          0
..  ...     ...    ...    ...        ...
95   12       1  104.0      0          0
96   51       1  101.0      1          1
97   20       1  101.0      0          0
98    5       1   98.0      1          0
99   10       1   98.0      1          1

[100 rows x 5 columns]

# Step2: Data Dividation

In [104]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [107]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   71.00  80.00
mean   42.91    0.59  101.00   0.40
std    24.47    0.50    2.05   0.49
min     5.00    0.00   98.00   0.00
25%    20.00    0.00   99.50   0.00
50%    42.00    1.00  101.00   0.00
75%    65.00    1.00  103.00   1.00
max    84.00    1.00  104.00   1.00

# Step 3: Apply MinMaxScaling

In [108]:
from sklearn.preprocessing import MinMaxScaler

In [109]:
mn = MinMaxScaler()

In [111]:
x_train_mn = mn.fit_transform(x_train)

In [112]:
x_train_new = pd.DataFrame(x_train_mn, columns = x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  71.00  80.00
mean    0.48    0.59   0.50   0.40
std     0.31    0.50   0.34   0.49
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.25   0.00
50%     0.47    1.00   0.50   0.00
75%     0.76    1.00   0.83   1.00
max     1.00    1.00   1.00   1.00

# Output : 

Min : 0 
max : 1

In [114]:
df = pd.read_csv("placement.csv")

In [117]:
df.head(2)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [118]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2 , random_state= 42)

In [120]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   71.00  80.00
mean   42.91    0.59  101.00   0.40
std    24.47    0.50    2.05   0.49
min     5.00    0.00   98.00   0.00
25%    20.00    0.00   99.50   0.00
50%    42.00    1.00  101.00   0.00
75%    65.00    1.00  103.00   1.00
max    84.00    1.00  104.00   1.00

In [119]:
mn  = MinMaxScaler()

In [121]:
x_train_mn = mn.fit_transform(x_train)

In [122]:
x_train_new = pd.DataFrame(x_train_new,columns=x_train.columns)

In [123]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  71.00  80.00
mean    0.48    0.59   0.50   0.40
std     0.31    0.50   0.34   0.49
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.25   0.00
50%     0.47    1.00   0.50   0.00
75%     0.76    1.00   0.83   1.00
max     1.00    1.00   1.00   1.00