In [1]:
print("Day 8 ")

Day 8

OrdinalEncoder --> Categorical --> Numerical --> Specific position [0,1] / [1,0]

In [1]:
import numpy as np 
import pandas as pd

In [11]:
df = pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [12]:
df= df.dropna()

In [13]:
df = df.drop(columns=['city','age','fever'])

In [14]:
df.head(2)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],['No','Yes']])

In [19]:
oe_arr = oe.fit_transform(df)

In [20]:
oe_new = pd.DataFrame(oe_arr,columns= df.columns)

In [22]:
oe_new

    gender  cough  has_covid
0      0.0    0.0        0.0
1      0.0    0.0        1.0
2      0.0    0.0        0.0
3      1.0    0.0        0.0
4      1.0    0.0        0.0
..     ...    ...        ...
85     1.0    0.0        0.0
86     1.0    1.0        1.0
87     1.0    0.0        0.0
88     1.0    1.0        0.0
89     1.0    1.0        1.0

[90 rows x 3 columns]

# Second Way -->

In [23]:
df = pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [24]:
df =df.dropna()

In [25]:
df = df.drop(columns=['age','fever','city'])

In [26]:
df.head(3)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes
2   Male  Mild        No

In [27]:
x = df.drop(columns=['has_covid'])
y=df['has_covid']

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
x.head(2)

  gender cough
0   Male  Mild
1   Male  Mild

In [31]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong']])

In [33]:
oe_arr_input = oe.fit_transform(x)

In [34]:
y.head(3)

0     No
1    Yes
2     No
Name: has_covid, dtype: str

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
lb = LabelEncoder()

In [38]:
y = lb.fit_transform(y)

In [39]:
# LabelEncoder ---> when we have single column . we cannot set sub-category form .
# has_covid['yes','no'] ---> labelecoder --> [1,0]
# OrdinalEncoder ---> when we have multiple columns .we can set sub-category form.
# has_covid['yes','no'] ---> ord. encoder ---> [0,1]

In [40]:
# first approach ::::
# df ---> categorical column ---> ordinal encoder ---> data transform
# second approach ::::
# df ---> x,y --->
# x ---> encode by Ordinal Encoder
# y ---> encode by Label Encoder

In [41]:
# tips data --->
# target column 'total_bill'
# Numerical columns ---> remove
# Categorical column ---> OrdinalEncoder

Tips DataSet OrdinalEncoder Working

In [97]:
df = pd.read_csv('tips.csv')
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [98]:
df =df.dropna()

In [99]:
df = df.drop(columns=['tip','total_bill','size'])

In [100]:
df.head(3)

      sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner
2    Male     No  Sun  Dinner

In [101]:
from sklearn.preprocessing import OrdinalEncoder

In [102]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Yes','No'],['Fri','Sat','Sun','Thur'],['Dinner','Lunch']])

In [103]:
oe_arr = oe.fit_transform(df)

In [104]:
new_oe = pd.DataFrame(oe_arr,columns=df.columns)

In [105]:
new_oe

     sex  smoker  day  time
0    1.0     1.0  2.0   0.0
1    0.0     1.0  2.0   0.0
2    0.0     1.0  2.0   0.0
3    0.0     1.0  2.0   0.0
4    1.0     1.0  2.0   0.0
..   ...     ...  ...   ...
239  0.0     1.0  1.0   0.0
240  1.0     0.0  1.0   0.0
241  0.0     0.0  1.0   0.0
242  0.0     1.0  1.0   0.0
243  1.0     1.0  3.0   0.0

[244 rows x 4 columns]