In [109]:
import numpy as np
import pandas as pd

In [110]:
df = pd.read_csv('tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [111]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [112]:
from sklearn.preprocessing import LabelEncoder

In [113]:
lb =LabelEncoder()

In [114]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['day'] = lb.fit_transform(df['day'])
df['time'] = lb.fit_transform(df['time'])

In [115]:
x = df.drop(columns=['total_bill'])
y =df['total_bill']

In [116]:
from sklearn.model_selection import train_test_split

In [117]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=42)

In [118]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [119]:
transformer = ColumnTransformer(transformers=[
    ('tnf1' ,SimpleImputer(),['sex'])
],remainder='passthrough')

In [120]:
transformer.fit_transform(x_train).shape

(195, 6)

In [121]:
df = pd.read_csv('tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [122]:
a = pd.get_dummies(df , columns=['sex','smoker','day','time'],drop_first=True)

In [123]:
a.astype(int)

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16,1,2,0,0,0,1,0,0
1,10,1,3,1,0,0,1,0,0
2,21,3,3,1,0,0,1,0,0
3,23,3,2,1,0,0,1,0,0
4,24,3,4,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
239,29,5,3,1,0,1,0,0,0
240,27,2,2,0,1,1,0,0,0
241,22,2,2,1,1,1,0,0,0
242,17,1,2,1,0,1,0,0,0
243,18,3,2,0,0,0,0,1,0

In [124]:
from sklearn.preprocessing import OneHotEncoder

In [125]:
ohe = OneHotEncoder(sparse_output=False , drop='first')

In [126]:
a = ohe.fit_transform(df[['sex' ,'smoker' , 'day' , 'time']])
a

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       ...,
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], shape=(244, 6))

In [127]:
pd.DataFrame(a)

       0    1    2    3    4    5
0    0.0  0.0  0.0  1.0  0.0  0.0
1    1.0  0.0  0.0  1.0  0.0  0.0
2    1.0  0.0  0.0  1.0  0.0  0.0
3    1.0  0.0  0.0  1.0  0.0  0.0
4    0.0  0.0  0.0  1.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...
239  1.0  0.0  1.0  0.0  0.0  0.0
240  0.0  1.0  1.0  0.0  0.0  0.0
241  1.0  1.0  1.0  0.0  0.0  0.0
242  1.0  0.0  1.0  0.0  0.0  0.0
243  0.0  0.0  0.0  0.0  1.0  0.0

[244 rows x 6 columns]

In [128]:
print("Pratice Of The Standardlization or Normalization")

Pratice Of The Standardlization or Normalization

In [129]:
import numpy as np
import pandas as pd

In [130]:
df = pd.read_csv('covid_toy.csv')

In [131]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [132]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [133]:
df = df.drop(columns=['fever'])

Categorical To numerical LaberEncoder

In [134]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [135]:
df['gender'] = lb.fit_transform(df['gender'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])
df['cough'] = lb.fit_transform(df['cough'])

Data Dividation

In [136]:
from sklearn.model_selection import train_test_split

In [137]:
x =df.drop(columns=['has_covid'])
y = df['has_covid']

In [138]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

Standardlization

In [139]:
from sklearn.preprocessing import StandardScaler

In [140]:
sc = StandardScaler()

In [141]:
x_train_sc = sc.fit_transform(x_train)

In [142]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [143]:
np.round(x_train_new.describe(),2)

         age  gender  cough   city
count  80.00   80.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01
min    -1.56   -0.84  -0.82  -1.17
25%    -0.94   -0.84  -0.82  -1.17
50%    -0.04   -0.84  -0.82  -0.27
75%     0.91    1.19   1.22   0.63
max     1.69    1.19   1.22   1.53

Normilization

In [144]:
from  sklearn.preprocessing import MinMaxScaler

In [145]:
mn = MinMaxScaler()

In [146]:
x_train_mn = mn.fit_transform(x_train)
x_trian_mn_new = pd.DataFrame(x_train_mn, columns=x_train.columns)

In [147]:
np.round(x_trian_mn_new.describe(),2)

         age  gender  cough   city
count  80.00   80.00  80.00  80.00
mean    0.48    0.41   0.40   0.43
std     0.31    0.50   0.49   0.37
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.00   0.00
50%     0.47    0.00   0.00   0.33
75%     0.76    1.00   1.00   0.67
max     1.00    1.00   1.00   1.00

# OneHotEncoding

In [148]:
df = pd.read_csv('covid_toy.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [149]:
ohe = OneHotEncoder(sparse_output=False ,drop='first')

In [150]:
a=ohe.fit_transform(df[['gender', 'cough' ,'city' , 'has_covid']])

In [151]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]