In [ ]:
print("Data Dividation")

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("covid_toy.csv")

In [3]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [6]:
cat_col = df.select_dtypes(include=['str','object']).columns

In [7]:
cat_col

Index(['gender', 'cough', 'city', 'has_covid'], dtype='str')

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
lb = LabelEncoder()

In [12]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [13]:
df

    age  gender  fever  cough  city  has_covid
0    60       1  103.0      0     2          0
1    27       1  100.0      0     1          1
2    42       1  101.0      0     1          0
3    31       0   98.0      0     2          0
4    65       0  101.0      0     3          0
..  ...     ...    ...    ...   ...        ...
95   12       0  104.0      0     0          0
96   51       0  101.0      1     2          1
97   20       0  101.0      0     0          0
98    5       0   98.0      1     3          0
99   10       0   98.0      1     2          1

[100 rows x 6 columns]

In [18]:
from sklearn.model_selection import train_test_split

In [ ]:
x = df.drop(columns=['has_covid']) # indepedent
y = df['has_covid'] # depedent

In [20]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2 , random_state=42)

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc = StandardScaler()

In [30]:
sc_new = sc.fit_transform(x_train)

In [32]:
sc_new_df = pd.DataFrame(sc_new , columns= x_train.columns)

In [34]:
d = np.round(sc_new_df.describe(),2)

In [37]:
d

         age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.84  -1.47  -0.82  -1.17
25%    -0.94   -0.84  -0.74  -0.82  -1.17
50%    -0.04   -0.84   0.00  -0.82  -0.27
75%     0.91    1.19   0.98   1.22   0.63
max     1.69    1.19   1.47   1.22   1.53

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
mn = MinMaxScaler()

In [40]:
mns__ = mn.fit_transform(x_train)
mns__1 = pd.DataFrame(mns__ , columns=x_train.columns)

In [44]:
np.round(mns__1.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean    0.48    0.41   0.50   0.40   0.43
std     0.31    0.50   0.34   0.49   0.37
min     0.00    0.00   0.00   0.00   0.00
25%     0.19    0.00   0.25   0.00   0.00
50%     0.47    0.00   0.50   0.00   0.33
75%     0.76    1.00   0.83   1.00   0.67
max     1.00    1.00   1.00   1.00   1.00

In [46]:
#      age	gender	fever	cough	city
#  count	80.00	80.00	71.00	80.00	80.00
#  mean	0.48	0.41	0.50	0.40	0.43
#  std	0.31	0.50	0.34	0.49	0.37
'''#  min	0.00	0.00	0.00	0.00	0.00'''
#  25%	0.19	0.00	0.25	0.00	0.00
#  50%	0.47	0.00	0.50	0.00	0.33
#  75%	0.76	1.00	0.83	1.00	0.67
'''#  max	1.00	1.00	1.00	1.00	1.00'''

'#  max\t1.00\t1.00\t1.00\t1.00\t1.00'

# Train_test_split

In [1]:

# data --> (1).Labled (Supervised ml) (Target Data Is Given) --> (2). Unlabled (unsupervised) (target data is not given)

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("california_housing_train.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [12]:
x = df.drop(columns=['median_house_value']) # indepedent Column
y = df['median_house_value'] # depedendant

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train , x_test , y_train ,y_test = train_test_split(x,y,test_size=0.2 , random_state=42)