In [171]:
import pandas as pd
import numpy as np

In [172]:
df = pd.read_csv('/content/covid_toy.csv')

In [173]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [174]:
from sklearn.preprocessing import LabelEncoder

In [175]:
lb = LabelEncoder()

In [176]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
# df['has_covid'] = lb.fit_transform(df['has_covid'])

In [177]:
x = df.drop(columns= ['has_covid'])
y = df['has_covid']

In [178]:
from sklearn.model_selection import train_test_split

In [179]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2  , random_state=42)

In [180]:
from sklearn.ensemble import  RandomForestClassifier

In [181]:
R = RandomForestClassifier()

In [182]:
R.fit(x_train , y_train)

RandomForestClassifier()

In [183]:
y_pred = R.predict(x_test)

In [184]:
from sklearn.metrics import accuracy_score

In [185]:
accuracy_score(y_test , y_pred)

0.5

In [186]:
df = pd.read_csv('/content/insurance.csv')

In [187]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [188]:
from sklearn.preprocessing import LabelEncoder

In [189]:
lb = LabelEncoder()

In [190]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

In [191]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [192]:
x = df.drop(columns=['charges'])
y = df['charges']

In [193]:
from sklearn.model_selection import train_test_split

In [194]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size= 0.2 , random_state = 42)

In [195]:
from sklearn.linear_model import LinearRegression

In [196]:
lr = LinearRegression()

In [197]:
lr.fit(x_train , y_train)

LinearRegression()

In [198]:
y_pred = lr.predict(x_test)

In [199]:
from sklearn.metrics import r2_score

In [200]:
r2_score(y_test , y_pred)

0.7833463107364539